/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author XT
 */
public class FrmMenu extends javax.swing.JFrame {

  /**
   * Creates new form FrmPlanes
   */
  public FrmMenu() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    btnRegistrarCurso = new javax.swing.JButton();
    btnAsignarRequisitos = new javax.swing.JButton();
    btnRgistrarPlanes = new javax.swing.JButton();
    btnConsultarPlanes = new javax.swing.JButton();
    btnEscuela = new javax.swing.JButton();
    btnAnadirCursoPlan = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Menu Principal");

    btnRegistrarCurso.setText("Registrar Curso");
    btnRegistrarCurso.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegistrarCursoActionPerformed(evt);
      }
    });

    btnAsignarRequisitos.setText("Asignar Requisitos y Correquisitos");

    btnRgistrarPlanes.setText("Registrar Planes");

    btnConsultarPlanes.setText("Consultar Planes");
    btnConsultarPlanes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsultarPlanesActionPerformed(evt);
      }
    });

    btnEscuela.setText("Registrar Escuela");

    btnAnadirCursoPlan.setText("Añadir Curso a Plan");
    btnAnadirCursoPlan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAnadirCursoPlanActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(88, 88, 88)
            .addComponent(jLabel1))
          .addGroup(layout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnRgistrarPlanes)
              .addComponent(btnEscuela)
              .addComponent(btnRegistrarCurso)))
          .addComponent(btnAsignarRequisitos)
          .addGroup(layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnAnadirCursoPlan)
              .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnConsultarPlanes)))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnEscuela)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnRgistrarPlanes)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnRegistrarCurso)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAsignarRequisitos)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAnadirCursoPlan)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnConsultarPlanes)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnRegistrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCursoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnRegistrarCursoActionPerformed

  private void btnConsultarPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPlanesActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnConsultarPlanesActionPerformed

  private void btnAnadirCursoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirCursoPlanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnAnadirCursoPlanActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrmMenu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnAnadirCursoPlan;
  public javax.swing.JButton btnAsignarRequisitos;
  public javax.swing.JButton btnConsultarPlanes;
  public javax.swing.JButton btnEscuela;
  public javax.swing.JButton btnRegistrarCurso;
  public javax.swing.JButton btnRgistrarPlanes;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
